# Generated by Django 4.0.1 on 2022-02-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='piece',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artist'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.buyer'),
        ),
    ]
