# Generated by Django 4.0.1 on 2022-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artist_email_buyer_company_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selllog',
            name='stat',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
