# Generated by Django 4.0.1 on 2022-02-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artwork_piece_alter_artwork_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='SellLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.artwork')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.buyer')),
            ],
        ),
    ]
