# Generated by Django 4.0.1 on 2022-02-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_selllog_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='company',
        ),
    ]
