# Generated by Django 4.0.1 on 2022-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_price_selllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='selllog',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
