# Generated by Django 4.0.1 on 2022-02-01 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0004_selllog_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
