# Generated by Django 4.0.1 on 2022-02-01 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0006_remove_artist_phone_remove_buyer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selllog',
            name='stat',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.CharField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.webuser'), max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='webUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.webuser'),
        ),
        migrations.AlterField(
            model_name='selllog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.webuser'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
