# Generated by Django 4.0.1 on 2022-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_artwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('On Sale', 'On Sale'), ('Sold', 'Sold')], max_length=200, null=True),
        ),
    ]
