# Generated by Django 4.0.1 on 2022-02-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_artwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.buyer'),
        ),
    ]
