# Generated by Django 4.0.1 on 2022-02-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_artwork_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='lname',
        ),
    ]
