# Generated by Django 4.0.1 on 2022-02-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_remove_artist_fname_remove_artist_lname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
        migrations.RemoveField(
            model_name='selllog',
            name='stat',
        ),
        migrations.AddField(
            model_name='selllog',
            name='status',
            field=models.CharField(choices=[('On Sale', 'On Sale'), ('Sold', 'Sold')], max_length=200, null=True),
        ),
    ]
