# Generated by Django 4.0.1 on 2022-02-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_remove_artwork_status_remove_selllog_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selllog',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='gallery.artwork'),
        ),
    ]
