# Generated by Django 4.0.1 on 2022-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_alter_selllog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selllog',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
