# Generated by Django 4.0.1 on 2022-02-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_alter_selllog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='piece',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
