# Generated by Django 4.0.1 on 2022-02-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_artwork_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.buyer'),
        ),
    ]
