# Generated by Django 4.0.1 on 2022-02-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_alter_artwork_date_created_alter_selllog_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.buyer'),
        ),
    ]
